export default {
    'Node': 'nodeIcon.png',
    'TypeScript':'typescriptIcon.png',
    'Css': 'cssIcon.png',
    'Html': 'htmlIcon.png',
    'Express.js': 'expressIcon.png',
    'Flask': 'flaskIcon.png',
    'Vercel': 'vercelIcon.png',
    'Php': 'phpIcon.png',
    'Vue': 'vue.ico',
    'Python' : 'pythonIcon.png',
    'Javascript': 'javascriptIcon.png',
    'Laravel': 'laravelIcon.png',
    'Web-socket' : 'webSocketIcon.png',
    'Heroku' : 'herokuIcon.png',
    'MongoDB' : 'mongodbIcon.png',
    'MySql' : 'mysqlIcon.png',
    'Git Hub' : 'githubIcon.png',
    'Git' : 'gitIcon.png',
    'GitLab' : 'gitlab.icon',
    'Sql Server' : 'sqlserverIcon.png',
    'Linkedin' : 'linkedinIcon.png',
    'Whats App' : 'whatsappIcon.png'
}